#!/bin/bash
mv /Applications/Cydia.app/icon-72.png.new /Applications/Cydia.app/icon-72.png
mv /Applications/Cydia.app/icon-72@2x.png.new /Applications/Cydia.app/icon-72@2x.png
mv /Applications/Cydia.app/Icon-Small-50.png.new /Applications/Cydia.app/Icon-Small-50.png
mv /Applications/Cydia.app/Icon-Small-50@2x.png.new /Applications/Cydia.app/Icon-Small-50@2x.png
mv /Applications/Cydia.app/Icon-Small.png.new /Applications/Cydia.app/Icon-Small.png
mv /Applications/Cydia.app/Icon-Small@2x.png.new /Applications/Cydia.app/Icon-Small@2x.png
mv /Applications/Cydia.app/icon.png.new /Applications/Cydia.app/icon.png
mv /Applications/Cydia.app/icon@2x.png.new /Applications/Cydia.app/icon@2x.png
mv /Applications/Cydia.app/iconClassic.png.new /Applications/Cydia.app/iconClassic.png
echo "new icon ready to use!"
exit 0
